# Generated by Django 5.1.7 on 2025-03-20 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_booking_status_alter_booking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='table',
            name='seats_count',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Столик', max_length=50, verbose_name='Название столика'),
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(db_index=True, default=2, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступен'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('table', 'booking_date'), name='unique_booking'),
        ),
    ]
